fn main() {
    if let Ok(config_rs) = std::env::var("DEP_PYTHONXY_DEFAULT_PYTHON_CONFIG_RS") {
        println!(
            "cargo:rustc-env=PYOXIDIZER_DEFAULT_PYTHON_CONFIG_RS={}",
            config_rs
        );
    } else {
        panic!("unable to find build artifacts generated by pyembed crate");
    }
}
