= Collect documentation from Rust code

This little helper library contains a `CollectDocs` derive macro.
Add it to your structs like this:

[source,rust]
----
include::examples/foo.rs[]
----

And get documentation like this
(with the correct heading that does not work in quoted asciidoc):

====
include::examples/Foo.adoc[]
====

== Examples

Examples are added in separate attributes
that specify the file type followed by the content.
They will be included as code blocks with the heading "Example".

=== Tests

Examples in YAML format will also be turned into tests
that exercise that the given content can be parsed by
item the example is on.
For structs, you should give it the full content of the struct,
for fields you neded to also include the field name
in the formatting serde expects (i.e., respecting `#[serde(rename="other_name")]`).

[source,console]
----
running 2 tests
test test_Foo_baz_example_0 ... ok
test test_Foo_example_0 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
---
