= Layouts

Layouts are defined in YAML files
stored in the `layouts/` directory of the `.kbdgen` bundle.
Their name has to be in ISO 639-1 or 639-3 format
and will be used when generating outputs.

// FIXME: Adapted from internalName. Is this true?
CAUTION: *The layout file names SHOULD NOT change between versions!*
If you change this, targets such as Android will display unexpected behaviour
when you update your keyboards.

== Structure of a layout descriptor file

Layout descriptors, like project descriptors, are defined using YAML.

At the highest level, a layout consists of several modes which define how the
layout should behave when different layers are enabled. There are distinct modes
for mobile and desktop keyboards, and the same layout file may incorporate
both modes if the user desires.

// FIXME: Obsolete?
// Layouts support a `supportedTargets` property so that a layout may be defined to
// only function with certain targets. This allows the keyboard developer to separate
// Windows layouts from Mac layouts, or separate mobile from desktop layouts, depending
// on the relevant use case for the developer.

Keys and transform outputs may be multi-codepoint. Simply type the output you expect in
the descriptor and it will be generated correctly, as layout modes are space-delimited only.

If you wish to input a unicode codepoint that causes distortion to the layout descriptor,
you may use `\u{x}` notation, which is just the `U+xxxx` codepoint written as `\u{xxxx}`. The
Examples section shows this in use several times.

// FIXME: Replaced by file name?
// NOTE: It is of fundamental importance that the `internalName` for each layout is
// unique. While the `kbdgen` generator should have an error in the case of user error,
// it has previously caused undefined behaviour.

== Mobile layouts

Mobile layouts consist of the modes `default` and `shift`. These modes
are currently used with the `android` and `ios` targets.

Mobile layouts support the `longpress` property, which defines a space-delimited set of characters
to be able to be selected by the user when they long press the defined key.

// FIXME: Only time this comes up is in LayoutTargetAndroid. Same thing? Obsolete?
The `styles` property defines the behaviour of the special keys depending on the size and shape
of the device. *At the moment this property is required.* You may simply copy and paste this boilerplate
into your projects.

The `strings` property defines the strings to be shown on the spacebar and return keys. While these are not
strictly required, it is highly recommended that you set these before deploying into production for the best
user experience, particularly on iOS.

== Desktop layouts

A desktop layout consists of keys for each mode, and uses dead key definitions (using `deadKeys`) and a transforms map
(`transforms`) for defining key sequences to output specific glyphs. Transforms may be infinitely nested in this format,
it is up to the platform to determine how many levels of nesting are considered reasonable.

=== Desktop modes

Modes are defined as a space-delimited and newline-delimited set of characters for use as keys
on a keyboard. The expected keyboard layout is the ISO standard keyboard (not the ANSI US keyboard,
which has one less key).

.Example of a desktop mode key map
```
§ 1 2 3 4 5 6 7 8 9 0 + ´
  á w e r t y u i o p å ŋ
  a s d f g h j k l ö ä '
< z x c v b n m , . -
```

.The ISO standard keyboard layout showing potential variations in colour
image::./keyboard.svg[]

`kbdgen` supports E00–E12, D01–D12, C01–C12, and B00–10 as per traditional European ISO standard keyboards. In practice, for ANSI keyboards,
C12 moves to D13, and B00 is simply dropped altogether. B11 is not used on any modern keyboard, and E13 is largely ignored.

CAUTION: If you forget to add the `|` symbol after the mode key, you will encounter some fun parsing errors.
Don't forget the pipe!

Desktop layouts consist of several modes due to the complexity of desktop keyboards:

* `default`
* `shift`
* `caps`
* `caps+shift`
* `alt`
* `alt+shift`
* `caps+alt`
* `ctrl`

There are also a few target-specific modes for macOS due to the addition of the Command key on macOS
keyboards:

* `cmd`
* `cmd+shift`
* `cmd+alt`
* `cmd+alt+shift`

It is possible that further modes may be supported in the future if necessary.

NOTE: For a list of all supported properties of layouts, see <<Layout>> in the reference section below.

// FIXME: styles property still required?
// |styles
// |mobile styles map
// |No (Yes for mobile)
// |This boilerplate is currently required for mobile targets. It is targeted for deprecation.
//
// Just copy and paste it verbatim into your mobile layouts for a happy life.
//
// |[source,yaml]
// ----
// styles:
//   tablet:
//     actions:
//       backspace: [1, right, fill]
//       enter: [2, right, fill]
//       shift: [3, both, fill]
//   phone:
//     actions:
//       shift: [3, left, fill]
//       backspace: [3, right, fill]
// ----

== Examples

.Mobile layout example (Android)
[source,yaml]
----
include::examples/layout-android.yaml[]
----

.Windows desktop layout example
[source,yaml]
----
include::examples/layout-win.yaml[]
----

.macOS desktop layout example
[source,yaml]
----
include::examples/layout-mac.yaml[]
----

== Best practices

NOTE: These best practices are a work-in-progress. If you have a suggestion, please submit an issue on GitHub.

As you can see from the examples, in some cases, macOS and Windows keyboards diverge significantly enough that
two separate layouts are defined. While it is still possible to generate a macOS and Windows keyboard from the
same source, consider user expectations when decided whether or not to split the layouts into separate files.

== Generating layouts from CLDR with cldr2kbdgen

`kbdgen` includes a tool called `cldr2kbdgen`, which will convert a CLDR keyboard XML descriptor
into a fully functional `kbdgen` layout.

You can acquire a CLDR keyboard repository from the http://cldr.unicode.org/index/downloads[Unicode] website.
Choose the latest from the Data column, then select the `cldr-keyboards-x.y.z.zip` file.

WARNING: If converting a macOS keyboard and the E00 (top left) and B00 (bottom left) keys are flipped, this is a known
issue with some CLDR definitions. Add the `--osx` flag to the `cldr2kbdgen` command and it will auto-flip them back.

Usage is straightforward: `cldr2kbdgen <cldr-xml> <path/to/layout.yaml>`
