== Android

The Android target uses a fork of the Android Open Source Project's `LatinIME`
codebase to generate a custom keyboard for Android with the look and feel of the
native keyboard.

The target will automatically download the https://github.com/divvun/giella-ime[`giella-ime`]
dependency and cache it for future builds. The cache will automatically be invalidated upon
an update to the repository.

=== Requirements

You will need:

* http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[JDK 8 or higher]
* https://developer.android.com/studio/index.html#command-tools[Android SDK CLI Tools]

=== Installation and environment configuration

WARNING: You will need about 2.6 GB of free space to install the Android SDK dependencies.

.Installing the Android development environment
. Create a directory to host your Android SDK.
. Export `ANDROID_HOME` to point to this directory.
. Unzip the Android SDK CLI tools into `$ANDROID_HOME` (so you have `$ANDROID_HOME/tools`).
. Run `yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses` to accept the licenses.
. Run `$ANDROID_HOME/tools/bin/sdkmanager tools "build-tools;25.0.3" "extras;android;m2repository" ndk-bundle "platforms;android-25"` to install the required dependencies. This may take a long time, and will not show any progress of any kind.

You should save the `ANDROID_HOME` export into your `.profile` so the variable is set when your shell loads.

=== Project-level configuration and properties

// TODO: link to projects chapter
As described in the Projects chapter, some targets may require project-level
properties in order to generate the target.

.Android project properties
[%autowidth.spread, cols="m,d,d,a", options="header"]
|===
|Property
|Required
|Description
|Example

|packageId
|Yes
|The reverse-domain notation ID for the package
|[source,yaml]
packageId: com.example.mypackageid

|icon
|No (but recommended)
|Path to the icon file to be converted into the various
sizes required by Android, relative to project root.
|[source,yaml]
icon: icons/icon.png

|keyStore
|No (Yes for release builds)
|Path to the Android keystore (see "Generating keystores" section for more information)
|[source,yaml]
keyStore: my.keystore

|keyAlias
|No (Yes for release builds)
|The key to use within the provided keystore
|[source,yaml]
keyAlias: myprojectkey
|===

.A full example of the targets section for Android
[source,yaml]
----
targets:
  android:
    packageId: com.example.amazing.keyboards
    icon: icon.png
    keyStore: path/to/my/keystore
    keyAlias: alias_specified_during_generation
----

=== Layout-level configuration and properties

.Android layout properties
[%autowidth.spread, cols="m,d,d,a", options="header"]
|===
|Property
|Required
|Description
|Example

|minimumSdk
|No
|The API level that is the minimum supported for a keyboard. Useful for
limiting access to a keyboard where it is known several glyphs are missing on
older devices.

https://source.android.com/source/build-numbers.html[See the Android documentation for API versions compared
to OS version].

NOTE: The lowest API supported by this keyboard is API 16, but it _may_ work
on older variants.

|[source,yaml]
minimumSdk: 16

|showNumberHints
|No (defaults to `true`)
|Defines whether or not the number hints are shown on the top row of keys.

When set to `false`, no number hints will be shown and any long press keys 
defined will be shown in their place.
|[source,yaml]
showNumberHints: true
|===

=== Testing

==== Testing on a device

[NOTE]
====
Different versions of Android have different requirements for enabling 
Developer Mode. Use a search engine to find out how to enable USB debugging 
for your specific device before continuing.
====

.Connecting an Android device for debugging
. Connect your Android device to your system
. Run `$ANDROID_HOME/platform-tools/adb install -r <path to apk>`

If you receive an error about the package already being installed or signatures
not matching, uninstall the package from the device first.

=== Generating keystores

CAUTION: Use ASCII characters only for your password if you value your sanity.

Make sure you've read the
http://developer.android.com/tools/publishing/app-signing.html["Signing Your Applications"]
page from the Android Developers website.

It is recommended that you use 4096-bit keys, and name the keystore and
alias your key with the internal name of your project.

For example, if my project name was "sami_keyboard", and I wanted the key to
last for 10000 days, I would run the following command:

`keytool -genkey -v -keystore sami_keyboard.keystore -alias sami_keyboard -keyalg RSA -keysize 4096 -validity 10000`

[WARNING]
====
**Make sure you keep your key safe! Don't publish it to git or svn.**
====

.The warning straight from the Android website says:
[quote]
____
Warning: Keep your keystore and private key in a safe and secure place,
and ensure that you have secure backups of them. If you publish an app to
Google Play and then lose the key with which you signed your app, you will
not be able to publish any updates to your app, since you must always sign
all versions of your app with the same key.
____