= Android

The Android target uses a fork of the Android Open Source Project's `LatinIME`
codebase to generate a custom keyboard for Android with the look and feel of the
native keyboard.

== Requirements

Due to the complexity and number of dependencies necessary to successfully build an
Android keyboard, we only support using our custom-built Docker image which includes
all the Rust and Android build tools and dependencies necessary to deliver a functioning
keyboard.

[source,console]
-----
docker pull divvun/kbdgen-android
-----

== Project-level configuration and properties

NOTE: For a list of all supported properties of the Android target files, see <<TargetAndroid>> in the reference section below.

.A full example of the targets section for Android
[source,yaml]
----
packageId: com.example.mykeyboard
keyStore: /secret/dir/safe.keystore
keyAlias: fancy_keyboard
version: 0.1.0
build: 1
----

== Layout-level configuration and properties

NOTE: See <<LayoutTargetAndroid>> in the reference section below.

== Testing

=== Testing on a device

[NOTE]
====
Different versions of Android have different requirements for enabling
Developer Mode. Use a search engine to find out how to enable USB debugging
for your specific device before continuing.
====

.Connecting an Android device for debugging
. Connect your Android device to your system
. Run `$ANDROID_HOME/platform-tools/adb install -r <path to apk>`

If you receive an error about the package already being installed or signatures
not matching, uninstall the package from the device first.

== Generating keystores

CAUTION: Use ASCII characters only for your password if you value your sanity.

Make sure you've read the
http://developer.android.com/tools/publishing/app-signing.html["Signing Your Applications"]
page from the Android Developers website.

It is recommended that you use 4096-bit keys, and name the keystore and
alias your key with the internal name of your project.

For example, if my project name was "sami_keyboard", and I wanted the key to
last for 10000 days, I would run the following command:

`keytool -genkey -v -keystore sami_keyboard.keystore -alias sami_keyboard -keyalg RSA -keysize 4096 -validity 10000`

[WARNING]
====
**Make sure you keep your key safe! Don't publish it to git or svn.**
====

.The warning straight from the Android website says:
[quote]
____
Warning: Keep your keystore and private key in a safe and secure place,
and ensure that you have secure backups of them. If you publish an app to
Google Play and then lose the key with which you signed your app, you will
not be able to publish any updates to your app, since you must always sign
all versions of your app with the same key.
____
