= iOS

The iOS target uses a fork of the https://github.com/archagon/tasty-imitation-keyboard[`tasty-imitation-keyboard`]
project to generate a custom keyboard for iOS with the look and feel of the
native keyboard.

The target will automatically download the https://github.com/divvun/giellakbd-ios[`giellakbd-ios`]
dependency and cache it for future builds. The cache will automatically be invalidated upon
an update to the repository.

== Requirements

You will need:

* Xcode
* Rust

Run the following:

....
rustup target add aarch64-apple-ios
rustup target add armv7-apple-ios
rustup target add i386-apple-ios
rustup target add x86_64-apple-ios
cargo install cargo-lipo
....

// = Installation and environment configuration
// TODO: will be needed once hfst-ospell-rust is integrated

== Project-level configuration and properties

NOTE: For a list of all supported properties of the iOS target files, see <<TargetIOS>> in the reference section below.

.Example of the targets section for iOS
[source,yaml]
----
codeSignId: "iPhone Distribution: The University of Tromso (666000999)"
provisioningProfileId: Test
packageId: com.example.mypackageid
bundleName: New Fancy Keyboards
version: 0.1.0
build: 1
----

== Layout-level configuration and properties

NOTE: See <<LayoutTargetIOS>> in the reference section below.

.Example of the layout-level targets section for iOS
[source,yaml]
----
targets:
  ios:
    legacyName: northern_sami_keyboa
----

== Testing

=== Testing in a simulator

[WARNING]
====
The simulator does not always fully replicate the behaviour that a user will
experience when using keyboards on a real device.

This is especially the case regarding when and where a keyboard can be used in
the simulator.

The best app for testing keyboards in the simulator is the `Calendar` app. It offers
a consistent experience and does not often cause obscure and unreproducable issues
when compared with other simulator apps.
====

To begin testing in the simulator is straightforward. Open the path provided by
`kbdgen` after a completed build in Xcode, choose a simulator device from the dropdown
in the main toolbar, and press the "Play" button.

Follow the instructions in the provided hosting app to enable the keyboards.

// == Testing on a device
