= macOS

CAUTION: This section is incomplete.

The `osx` target generates a `.pkg` file, optionally codesigned, that installs a series of `.keylayout` files for each layout provided in the project.

To sign the package, specify the `-R` flag while building.

== Requirements

WARNING: This target can only be generated on a macOS system.

You need to install:

* ImageMagick

== Project-level configuration and properties

NOTE: For a list of all supported properties of the iOS target files, see <<TargetMacOS>> in the reference section below.

[source,yaml]
----
codeSignId: 'Developer ID Installer: The University of Tromso (666000999)'
provisioningProfileId: Test
packageId: com.example.mypackageid
bundleName: New Fancy Keyboards
icon: images/icon.png
version: 1.0.4
build: 1
----

`icon` will be converted into an `.icns` file.

`codeSignId` must be for a macOS installer distribution certificate, generated by the Team Agent.

Resources can be localised. Place readme, welcome, license and conclusion files into `zz.lproj` directories inside the resources directory, where `zz` represents a supported language code. Place the background image into the root of the resources directory.

== Layout-level configuration and properties

The macOS target supports a few custom modes to facilitate the differences between macOS keyboards and others. Particularly, the `cmd` key is macOS specific.

// FIXME: Is this still valid?
// If you wish to use your `iso-default` mode as the `osx-cmd` mode (which is the sanest default), you can use YAML referencing:
//
// [source,yaml]
// ----
// iso-default: | &default
//   my keyboard here
// osx-cmd: *default
// ----

