WARNING: Each target may have separate requirements for generating and building the output that `kbdgen` provides. Please check the Installation section of your desired target before proceeding.

=== From Source

==== Unix-like (Linux, macOS, etc)

You will need Python {pyversion} or higher installed to continue. Use your operating system's package manager to install the `python3` package or equivalent. You will also need to install `poetry`, a Python package management tool.

[source]
----
poetry install
----

You will also need to install `imagemagick` or icon generation (and therefore the build) will fail for several targets. On 
macOS, this can be installed with MacPorts or Homebrew. (`brew install imagemagick` or `port install imagemagick`).

==== Windows

Ensure Python {pyversion} or higher is installed on your system and Python's executables are available in your `%PATH%`. You will also need to install `poetry`, a Python package management tool. Using the Command Prompt, run the following commands:

[source]
----
poetry install
----

It is left an exercise for the reader to work out how to install `imagemagick` on Windows and add it to the `%PATH%`.
